### PR TITLE
Some small tweaks and conformance things

### PR DESCRIPTION
**Pull request by rocky**
These were the few only remaining things I found. After this I  think we should merge split_main into master.

### CODE REVIEW

**Review by mmatera — APPROVED** [review]
LGTM

**Comment by mmatera** [comment]
Let's merge this, and then the other branch

**Comment by mmatera** [comment]
BTW, thank you very much @rocky  for the fixes and revision.

**Comment by rocky** [comment]
And thank you for doing the bulk of the hard work. With this in, I think we _finally_ ready for the 6.0.0 release this weekend. (Early Saturday I'll be working with @TiagoCavalcante to see if we can address why we can't use the most recent mathics-threejs-backend. If there is a change needed to mathics-core, we should be able to slip that in.) 

Whew!

**Comment by rocky** [comment]
> Let's merge this, and then the other branch

Yes, absolutely - thanks!

**Pull request merged**
